[build]
  base    = "AplicatieTransporturi/AplicatieTransporturi/frontend"
  command = "npm run build"
  publish = "AplicatieTransporturi/AplicatieTransporturi/frontend/dist/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
