[build]
  base    = "AplicatieTransporturi/frontend"
  command = "npm run build"
  publish = "AplicatieTransporturi/frontend/dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
