[[plugins]]
  package = "netlify-plugin-prerender-spa"
  [plugins.inputs]
    staticDir = "Aplicatie Transporturi/frontend/dist/frontend/browser"
    routes = [
      "/", "/drivers", "/drivers/add",
      "/vehicles", "/vehicles/add",
      "/deliveries", "/deliveries/add",
      "/drivers/edit/:id",
      "/vehicles/edit/:id",
      "/deliveries/edit/:id"
    ]
    getPrerenderParams = "prerender-params.js"
